name: Deploy to TheGraph
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: deploy
        run:
          yarn exec graph deploy --product hosted-service --access-token=${{ secrets.GRAPH_ACCESS_TOKEN }} 0xBeeDao/moloch-rises-subgraph
